name: Build, Package & Push Image to GHCR

on:
  push:
    branches: [ "develop" ]
    tags: [ "v*" ]
    paths:
      - '.github/workflows/package.yml'
      - 'src/**'
      - 'scripts/**'
      - '.python-version'
      - 'Procfile'
      - 'project.toml'
      - 'pyproject.toml'
      - 'requirements.txt'
      - 'uv.lock'
  workflow_dispatch:

jobs:
  scan-app:
    name: Scan the application for issues
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Scan for all vulnerabilities
        uses: aquasecurity/trivy-action@0.33.1
        with:
          scan-type: 'fs'
          scan-ref: '.'

      - name: Fail if there are high/critical vulnerabilities
        uses: aquasecurity/trivy-action@0.33.1
        with:
          scan-type: 'fs'
          scan-ref: '.'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'

  build-image:
    name: Build and publish a container image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: buildpacks/github-actions/setup-pack@v5.10.0

      - name: Build and publish container image
        run: ./scripts/package.sh
        env:
          PROJECT: .
          IMAGE_URI: ghcr.io/dmikusa/codemash-2026-mcp-demo:${{ github.ref_name }}

  scan-image:
    name: Scan the created container image
    runs-on: ubuntu-latest
    needs: build-image
    steps:
      - name: Scan container image
        uses: aquasecurity/trivy-action@0.33.1
        with:
          image-ref: ghcr.io/dmikusa/codemash-2026-mcp-demo:${{ github.ref_name }}
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'
